# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/151242011/switch_2/switch_2.cache/wt [current_project]
set_property parent.project_path D:/151242011/switch_2/switch_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/151242011/switch_2/switch_2.srcs/sources_1/new/switch2.v
read_xdc D:/151242011/switch_2/switch_2.srcs/constrs_1/new/switch_xdc.xdc
set_property used_in_implementation false [get_files D:/151242011/switch_2/switch_2.srcs/constrs_1/new/switch_xdc.xdc]

synth_design -top switch2 -part xc7a100tcsg324-1
write_checkpoint -noxdef switch2.dcp
catch { report_utilization -file switch2_utilization_synth.rpt -pb switch2_utilization_synth.pb }
