# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/digital/decoder_1/decoder_1.cache/wt [current_project]
set_property parent.project_path D:/digital/decoder_1/decoder_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/digital/decoder_1/decoder_1.srcs/sources_1/new/seg7_1.v
read_xdc D:/digital/decoder_1/decoder_1.srcs/constrs_1/new/seg7_1.xdc
set_property used_in_implementation false [get_files D:/digital/decoder_1/decoder_1.srcs/constrs_1/new/seg7_1.xdc]

synth_design -top seg7_1 -part xc7a100tcsg324-1
write_checkpoint -noxdef seg7_1.dcp
catch { report_utilization -file seg7_1_utilization_synth.rpt -pb seg7_1_utilization_synth.pb }
